### ISSUE TITLE
Multiple selections copy/cut-paste

### ISSUE THREAD

**Issue by pidgeon777** [dail8859/BetterMultiSelection#9] opened 2019-02-13 08:54 UTC
In Sublime Text, when multiple words are selected and copied or cut, then those get also pasted in the respective positions marked by the cursors (which clearly need to be equal to the number of the initial selections). A demonstration follows below:

![img](https://s2.gifyu.com/images/multiEditVSCode.gif)

Do you think something like this could be implemented in BetterMultiSelection?

**Comment by dail8859** [comment] 2019-02-16 01:52
I did some playing around with the Win32 API to handle clipboard data. Seems doable. Just need to find some more free time to get it working properly.

**Comment by pidgeon777** [comment] 2019-02-16 22:07
Well, it would be absolutely great. Something which is really missing from Notepad++, and which would noticeably reduce the gap with other editors (Sublime Text, etc.).

**Comment by dail8859** [comment] 2019-02-21 00:04
This seems to be working in the limited testing I've done. It seems a bit hackish but functional. I'd appreciate any testing you can do to try to find any issues with it since it could potentially screw up basic copy/paste functionality. There are a few limitations but not sure if they are a problem or not, so for now I'll call it good enough. Here's a quick demo of what was shown above, but in Notepad++.

![multipaste](https://user-images.githubusercontent.com/3694843/53133637-d4bfd980-3541-11e9-9bb9-962aa43d2dd0.gif)

You can download the new builds here and copy over your existing DLL:

- 64-bit  https://ci.appveyor.com/project/dail8859/bettermultiselection/build/job/8xyr2g0tl7eg35te/artifacts
- 32-bit   https://ci.appveyor.com/project/dail8859/bettermultiselection/build/job/3a5shvx2ohqdqa8n/artifacts

**Comment by dail8859** [comment] 2019-02-21 00:11
Just realized I forgot all about cutting text and it only copies it currently. Will add that in later.

**Comment by pidgeon777** [comment] 2019-02-21 07:31
First of all, thank you.

I'll be more than happy to start testing this new feature right now, I'll let you know about the outcome in a couple of weeks. In the meanwhile, if time is on your side, I'll also test the cut - paste function once you'll release it.

I'm happy about this new enhancement, though, now Notepad++ editing experience is even more complete.

Just a final note: I noticed you also replicated the Ctrl + D function (multiple selections of comma character in your case), is this also included in your latest release or did you implement it by making use of a specific script engine (e.g. Python Script)? Just out of curiosity.

**Comment by pidgeon777** [comment] 2019-02-21 07:46
Hi, I downloaded your latest DLL (Notepad++ 7.6.3 32 bit) but it seems that BetterMultiSelection still is not capable of handling the copy of the multiple selections (those are still concatenated and pasted for each cursor). Please let me know if you need more info.

**Comment by dail8859** [comment] 2019-02-21 12:15
> I'll be more than happy to start testing this new feature right now

Very much appreciated!

>  I noticed you also replicated the Ctrl + D function

I've had this functionality for a while. I use LuaScript (another one of my plugins), and use code similar to this: http://dail8859.github.io/LuaScript/examples/selectionaddnext.lua.html

> it seems that BetterMultiSelection still is not capable of handling the copy of the multiple selections

Couple things come to mind. Notepad++ has changed the location of where the DLL is stored, can't recall exactly where 7.6.3 stores them off the top of my head. I'd make sure you are overwriting the correct one. Also, are you using a standard US keyboard layout or some other layout? 

And it is very possible I just have overlooked something in my code too. :)

**Comment by pidgeon777** [comment] 2019-02-21 13:44
Thanks for pointing out your LUA script location, I'll have a look at it.

Regarding BetterMultiSelection, I think it is correctly detected by Notepad++ because I can successfully move around the cursors as you have shown, the only malfunctioning thing is the copy - paste feature.

I'm using a keyboard with QWERTY layout (Italian model).

**Comment by dail8859** [comment] 2019-02-22 03:28
The more I think about it the keyboard layout should be fine since it is just looking at standard `Ctrl+C` and `Ctrl+V` shortcuts.

I think I know why it is not working though. If you change the file encoding to UTF-8 (Encoding > Encode in UTF-8) does copy/paste work for multiple cursors? This will obviously need fixed but want to verify that's the issue for you.

**Comment by pidgeon777** [comment] 2019-02-22 19:42
Congratulations, you got it right! Changing the file encoding to UTF-8 did indeed solve the issue. Do you think this behaviour could be easily fixed?

**Comment by dail8859** [comment] 2019-02-22 19:47
> Do you think this behaviour could be easily fixed?

Yes. My initial hackish way of doing was much future from complete than I had thought. I've already got a better implementation in place for part of it already.

**Comment by pidgeon777** [comment] 2019-02-22 20:11
Nice! I'll be more happy to test it as soon as it's ready.

**Comment by dail8859** [comment] 2019-02-23 19:03
Attempt number 2. I will keep this issue open for now.

- 32 bit: https://ci.appveyor.com/project/dail8859/bettermultiselection/build/job/lf4a5goshpaky7dc/artifacts
- 64 bit: https://ci.appveyor.com/project/dail8859/bettermultiselection/build/job/ea93vulrv2sxpq4j/artifacts

This should be alot more robust and implements cut/copy/paste. Again, any testing/comments/feedback is appreciated.

**Comment by pidgeon777** [comment] 2019-02-23 19:41
I'll test it over the next weeks. Thank you.

**Comment by dail8859** [comment] 2019-03-26 00:16
Closing for now and will get around to creating a release when I get a chance. Reopen if you have any issues.

**Comment by pidgeon777** [comment] 2019-03-26 13:08
Thanks for the update, sometimes your plugin stops working but I'm trying with difficulty to replicate the issue because it doesn't occur regularly. Please let me know if you need some details in particular.

Maybe there could be a way to enable debug output on your plugin to do some investigation?

**Comment by dail8859** [comment] 2019-03-30 15:31
Any details would would help narrow down the problem, such as if copying or pasting seems to cause it more. Also if you have other plugins installed that would be good to know. Probably just posting your debug info would be the most helpful. 

There is no logging currently but something could potentially be added.

**Comment by pidgeon777** [comment] 2019-03-31 11:57
Thank you. The more I use your plugin, the more I increase my productivity.

I found out another possible bug.

This is what I do:

1) Select 3 words
2) Ctrl + X
4) Select other 3 words
5) Ctrl + V

![0YYqsiWvRw](https://user-images.githubusercontent.com/13739892/55288701-bad4aa80-53bb-11e9-88d6-7c0a6f484c62.gif)

The previously cut words get appended to the new selection. I would expect those to replace the newly selected words. Does this represent the wanted behaviour?

Thank you again.

**Comment by dail8859** [comment] 2019-04-04 22:51
> I found out another possible bug.

Fixed in 3391d9d

**Comment by dail8859** [comment] 2019-04-25 23:43
Any luck reproducing the issue you were having earlier?

**Comment by cesarmtnez** [comment] 2019-05-24 12:42
Hi, I'm test the 1.3.0.12 version and ir works great, that new feature make better my life ;-).  Thank you.

I've try it but I could not reproduce the issue that you commented.

On the other hand, it will be fantastic if your plugin would be abble to remember the focus after make an 'undo' (Ctrl + Z). Now, after the 'undo' the focus goes to normal focus in a only line. (Maybe that's must go to open a new issue?)

**Comment by dail8859** [comment] 2019-05-24 13:23
Hi @cesarmtnez. Thanks for testing it out

If you would, go ahead and open a new issue so it can be discussed there.

**Comment by cesarmtnez** [comment] 2019-05-24 13:26
Ok, I will. Thank you.

**Comment by pidgeon777** [comment] 2019-06-05 06:28
> Any luck reproducing the issue you were having earlier?

Here I am again. Sorry for the wait. Over the past few months, the job kept me highly busy and I haven't had a chance to try your last release. I will do it right now.

Thanks again.

**Comment by pidgeon777** [comment] 2019-06-05 06:31
Just another question, is the binary with your latest fix downloadable somewhere?

**Comment by dail8859** [comment] 2019-06-05 11:18
> Sorry for the wait.

No problem at all. I understand what it is like to get very busy :)

> is it the one available here?

Yes, that is the latest DLL available.

**Comment by pidgeon777** [comment] 2019-06-05 11:34
Thank you for the prompt reply. I'm testing it right now :).

**Comment by dail8859** [comment] 2020-01-07 01:19
Closed by 72f7222

**Closed by dail8859** 2020-01-07 01:19 UTC
